# src/NOAH/PlatformBundle/Resources/config/services.yml

services:
    noah_platform.antispam:
        class: NOAH\PlatformBundle\Antispam\NOAHAntispam
        arguments:
            - "@mailer"
            - %locale%
            - 50


#services:
#    noah_platform.example:
#        class: NOAH\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

